server:
  port: 11003

eureka:
  instance:
    hostname: localhost
    eureka-server-port: 11000
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.eureka-server-port}/eureka/


spring:
  application:
    name: RabbitMQ
  rabbitmq:
    host: 39.104.49.76
    port: 5672
    username: root
    password: root
    publisher-confirms: true
    virtual-host: /




