spring:
  redis:
    database: 0
    port: 6379
    host: 39.104.49.76
    password: test123
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

